export const paths = {
  user: "/user",
  mail: "/mail",
  weekendMeal: "/weekend-meal",
  selfStudy: "/self-study",
  schedule: "/schedule",
  notice: "/notice",
  meal: "/meal",
  earlyReturn: "/early-return",
  classroom: "/class-room",
  bug: "/bug",
  application: "/application",
  afterSchool: "/after",
  timeTable: "/timetable",
};
